## Actualizar tarea
PATCH {{Api_HostAddress}}/tarea/update/2/6
Content-Type: application/json
Authorization: Bearer {{Token}}
{
    "titulo": "Tarea actualizada",
    "contenido": "Nueva descripción acerca de algo"
}

## Asingar tarea
PATCH {{Api_HostAddress}}/tarea/assing-task/3/53/6
Authorization: Bearer {{Token}}

## Finalizar tarea
PATCH {{Api_HostAddress}}/tarea/complete/3/6
Authorization: Bearer {{Token}}
