## Crear proyecto
POST {{Api_HostAddress}}/proyecto/create
Authorization: Bearer {{Token}}
Content-Type: application/json
{
    "nombre": "Mi Proyecto Personal 2"
}

## Agregar usuario
POST {{Api_HostAddress}}/proyecto/add/9
Authorization: Bearer {{Token}}
Content-Type: application/json
{
    "idUsuario": 54,
    "idRol": 40
}