## Actualizar proyecto
PATCH {{Api_HostAddress}}/proyecto/update/6
Content-Type: application/json
Authorization: Bearer {{Token}}
{
    "nombre": "Nuevo nombre de proyecto"
}

## Reasignar rol de usuario en proyecto
PATCH {{Api_HostAddress}}/proyecto/assing-rol/6
Content-Type: application/json
Authorization: Bearer {{Token}}
{
    "idUsuarioProyecto": 55,
    "idRol": 31,
    "idUsuario": 53
}

## Finalizar proyecto
PATCH {{Api_HostAddress}}/proyecto/finalized/6
Authorization: Bearer {{Token}}